################################################ PHASE 1 ################################################
image: golang:1.15.5

variables:
  PROJECT_NAME: "pfcli"

################################################ PHASE 2 ################################################

cache:
  paths:
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - quality
  - build
  - release
before_script:
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  #  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)
  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ##
  ## Optionally, if you will be using any Git commands, set the user name and
  ## and email.
  ##
  - git config --global user.email "bouagina.montassar@gmail.com"
  - git config --global user.name "ITMonta"
  ## Prepare go sources
  - mkdir -p /go/src/gitlab.com/nt-factory/2021/admin /go/src/_/builds/nt-factory/2021/admin
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/nt-factory/2021/admin/pfcli
  - ln -s /go/src/gitlab.com/nt-factory/2021/admin /go/src/_/builds/nt-factory/2021/admin
  - go get -v -d ./...
################################################ PHASE 3 ################################################


unit_tests:
  stage: test
  script:
    - go test -v ./...
build:
  stage: build
  script:
    - go build -i -v
release:
  stage: release
  image:
    name: goreleaser/goreleaser:latest
    entrypoint: [""]
  variables:
    GITLAB_TOKEN: "ewK3kecg7tg44Bq-Uwu6"
  script:
    - git tag -a v0.1.0 -m "First release"
    - git push origin v0.1.0
    - goreleaser release