################################################ PHASE 1 ################################################
image: golang:1.15.5

variables:
  PROJECT_NAME: "pfcli"

################################################ PHASE 2 ################################################

cache:
  paths:
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - quality
  - build
  - release
before_script:
  - mkdir -p /go/src/gitlab.com/nt-factory/2021/admin /go/src/_/builds/nt-factory/2021/admin
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/nt-factory/2021/admin/pfcli
  - ln -s /go/src/gitlab.com/nt-factory/2021/admin /go/src/_/builds/nt-factory/2021/admin
  - go get -v -d ./...
################################################ PHASE 3 ################################################


unit_tests:
  stage: test
  script:
    - go test -v ./...
build:
  stage: build
  script:
    - go build -i -v
release:
  stage: release
  image:
    name: goreleaser/goreleaser:latest
#    entrypoint: ["/bin/sh"]
  variables:
    GITLAB_TOKEN: "ewK3kecg7tg44Bq-Uwu6"
  script:
    - release